inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    - "config/rspec.yml"

inherit_from:
  - ".rubocop_todo.yml"

AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - "test/**/*"
    - "tmp/**/*"
    - "activerecord.rake"
