language: ruby
sudo: false

cache:
  bundler: true

rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - ruby-head

gemfile:
  - gemfiles/rails5_0.gemfile
  - gemfiles/rails_edge.gemfile

env:
  - SETUP_TASK=turntable:db:reset BUILD_TASK=spec
  - SETUP_TASK=turntable:activerecord:setup BUILD_TASK=turntable:activerecord:test

before_install: gem update --system

before_script:
  - bundle exec rake $SETUP_TASK

script:
  - bundle exec rake $BUILD_TASK

matrix:
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/rails_edge.gemfile
