language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - 2.2
  - ruby-head
gemfile:
  - gemfiles/rails4_0.gemfile
  - gemfiles/rails4_1.gemfile
before_script:
  - bundle exec rake turntable:db:reset
script: bundle exec rake spec
matrix:
  allow_failures:
    - rvm: 2.2
    - rvm: ruby-head
