language: ruby
sudo: false

cache:
  bundler: true

rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - ruby-head

gemfile:
  - gemfiles/rails5_0.gemfile

before_install: gem update --system
before_script: ci/setup-tests.sh
script: ci/run-tests.sh

matrix:
  allow_failures:
    - rvm: ruby-head
