language: ruby
rvm:
  - 1.9.2
  - 1.9.3
gemfile:
  - gemfiles/rails3_0.gemfile
  - gemfiles/rails3_1.gemfile
  - gemfiles/rails3_0.gemfile
before_script:
  - bundle exec rake turntable:db:reset
script: bundle exec rake spec

